using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ILEngineTests.Autogenerated
{
    /// <summary>
    /// Auto-generates comprehensive list of unit tests to cover all opcode instructions
    /// </summary>
    public class TestsAutoGenerator
    {
        public static void Generate()
        {
            // there are 226 given opcodes
            // from this
            
        }
    }

  
}
