using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace ILEngine
{
    public abstract class ILOpcodeActionGeneratorBase : IILOpcodeActionGenerator
    {
        protected Dictionary<int, Action> opcodeHandlers;
        protected Dictionary<int, OpcodeValueAttribute> opcodeValueAttributes;
        public ILOpcodeActionGeneratorBase()
        {

            opcodeHandlers = new Dictionary<int, Action>();
            opcodeValueAttributes = new Dictionary<int, OpcodeValueAttribute>();
            var methods = this.GetType().GetMethods();
            foreach (var method in methods)
            {
                var opcodeatt = GetOpcodeInfo(method);
                if (!(opcodeatt is null))
                {
                    Action action = (Action)Delegate.CreateDelegate(typeof(Action), this, method);
                    opcodeHandlers.Add(opcodeatt.OpcodeValue, action);
                    opcodeValueAttributes.Add(opcodeatt.OpcodeValue, opcodeatt);
                }
            }

        }

        OpcodeValueAttribute GetOpcodeInfo(MethodBase method) =>
            method.GetCustomAttributes(true).Where(x => x is OpcodeValueAttribute).FirstOrDefault() as OpcodeValueAttribute;


        public void GenerateAll()
        {
            GenerateNop();
            GenerateBreak();
            GenerateLdarg_0();
            GenerateLdarg_1();
            GenerateLdarg_2();
            GenerateLdarg_3();
            GenerateLdloc_0();
            GenerateLdloc_1();
            GenerateLdloc_2();
            GenerateLdloc_3();
            GenerateStloc_0();
            GenerateStloc_1();
            GenerateStloc_2();
            GenerateStloc_3();
            GenerateLdarg_S();
            GenerateLdarga_S();
            GenerateStarg_S();
            GenerateLdloc_S();
            GenerateLdloca_S();
            GenerateStloc_S();
            GenerateLdnull();
            GenerateLdc_I4_M1();
            GenerateLdc_I4_0();
            GenerateLdc_I4_1();
            GenerateLdc_I4_2();
            GenerateLdc_I4_3();
            GenerateLdc_I4_4();
            GenerateLdc_I4_5();
            GenerateLdc_I4_6();
            GenerateLdc_I4_7();
            GenerateLdc_I4_8();
            GenerateLdc_I4_S();
            GenerateLdc_I4();
            GenerateLdc_I8();
            GenerateLdc_R4();
            GenerateLdc_R8();
            GenerateExec_MSIL_I();
            GenerateDup();
            GeneratePop();
            GenerateJmp();
            GenerateCall();
            GenerateCalli();
            GenerateRet();
            GenerateBr_S();
            GenerateBrfalse_S();
            GenerateBrtrue_S();
            GenerateBeq_S();
            GenerateBge_S();
            GenerateBgt_S();
            GenerateBle_S();
            GenerateBlt_S();
            GenerateBne_Un_S();
            GenerateBge_Un_S();
            GenerateBgt_Un_S();
            GenerateBle_Un_S();
            GenerateBlt_Un_S();
            GenerateBr();
            GenerateBrfalse();
            GenerateBrtrue();
            GenerateBeq();
            GenerateBge();
            GenerateBgt();
            GenerateBle();
            GenerateBlt();
            GenerateBne_Un();
            GenerateBge_Un();
            GenerateBgt_Un();
            GenerateBle_Un();
            GenerateBlt_Un();
            GenerateSwitch();
            GenerateLdind_I1();
            GenerateLdind_U1();
            GenerateLdind_I2();
            GenerateLdind_U2();
            GenerateLdind_I4();
            GenerateLdind_U4();
            GenerateLdind_I8();
            GenerateLdind_I();
            GenerateLdind_R4();
            GenerateLdind_R8();
            GenerateLdind_Ref();
            GenerateStind_Ref();
            GenerateStind_I1();
            GenerateStind_I2();
            GenerateStind_I4();
            GenerateStind_I8();
            GenerateStind_R4();
            GenerateStind_R8();
            GenerateAdd();
            GenerateSub();
            GenerateMul();
            GenerateDiv();
            GenerateDiv_Un();
            GenerateRem();
            GenerateRem_Un();
            GenerateAnd();
            GenerateOr();
            GenerateXor();
            GenerateShl();
            GenerateShr();
            GenerateShr_Un();
            GenerateNeg();
            GenerateNot();
            GenerateConv_I1();
            GenerateConv_I2();
            GenerateConv_I4();
            GenerateConv_I8();
            GenerateConv_R4();
            GenerateConv_R8();
            GenerateConv_U4();
            GenerateConv_U8();
            GenerateCallvirt();
            GenerateCpobj();
            GenerateLdobj();
            GenerateLdstr();
            GenerateNewobj();
            GenerateCastclass();
            GenerateIsinst();
            GenerateConv_R_Un();
            GenerateExec_MSIL_S();
            GenerateUnbox();
            GenerateThrow();
            GenerateLdfld();
            GenerateLdflda();
            GenerateStfld();
            GenerateLdsfld();
            GenerateLdsflda();
            GenerateStsfld();
            GenerateStobj();
            GenerateConv_Ovf_I1_Un();
            GenerateConv_Ovf_I2_Un();
            GenerateConv_Ovf_I4_Un();
            GenerateConv_Ovf_I8_Un();
            GenerateConv_Ovf_U1_Un();
            GenerateConv_Ovf_U2_Un();
            GenerateConv_Ovf_U4_Un();
            GenerateConv_Ovf_U8_Un();
            GenerateConv_Ovf_I_Un();
            GenerateConv_Ovf_U_Un();
            GenerateBox();
            GenerateNewarr();
            GenerateLdlen();
            GenerateLdelema();
            GenerateLdelem_I1();
            GenerateLdelem_U1();
            GenerateLdelem_I2();
            GenerateLdelem_U2();
            GenerateLdelem_I4();
            GenerateLdelem_U4();
            GenerateLdelem_I8();
            GenerateLdelem_I();
            GenerateLdelem_R4();
            GenerateLdelem_R8();
            GenerateLdelem_Ref();
            GenerateStelem_I();
            GenerateStelem_I1();
            GenerateStelem_I2();
            GenerateStelem_I4();
            GenerateStelem_I8();
            GenerateStelem_R4();
            GenerateStelem_R8();
            GenerateStelem_Ref();
            GenerateLdelem();
            GenerateStelem();
            GenerateUnbox_Any();
            GenerateConv_Ovf_I1();
            GenerateConv_Ovf_U1();
            GenerateConv_Ovf_I2();
            GenerateConv_Ovf_U2();
            GenerateConv_Ovf_I4();
            GenerateConv_Ovf_U4();
            GenerateConv_Ovf_I8();
            GenerateConv_Ovf_U8();
            GenerateRefanyval();
            GenerateCkfinite();
            GenerateMkrefany();
            GenerateLdtoken();
            GenerateConv_U2();
            GenerateConv_U1();
            GenerateConv_I();
            GenerateConv_Ovf_I();
            GenerateConv_Ovf_U();
            GenerateAdd_Ovf();
            GenerateAdd_Ovf_Un();
            GenerateMul_Ovf();
            GenerateMul_Ovf_Un();
            GenerateSub_Ovf();
            GenerateSub_Ovf_Un();
            GenerateEndfinally();
            GenerateLeave();
            GenerateLeave_S();
            GenerateStind_I();
            GenerateConv_U();
            GeneratePrefix7();
            GeneratePrefix6();
            GeneratePrefix5();
            GeneratePrefix4();
            GeneratePrefix3();
            GeneratePrefix2();
            GeneratePrefix1();
            GeneratePrefixref();
            GenerateArglist();
            GenerateCeq();
            GenerateCgt();
            GenerateCgt_Un();
            GenerateClt();
            GenerateClt_Un();
            GenerateLdftn();
            GenerateLdvirtftn();
            GenerateLdarg();
            GenerateLdarga();
            GenerateStarg();
            GenerateLdloc();
            GenerateLdloca();
            GenerateStloc();
            GenerateLocalloc();
            GenerateEndfilter();
            GenerateUnaligned_();
            GenerateVolatile_();
            GenerateTail_();
            GenerateInitobj();
            GenerateConstrained_();
            GenerateCpblk();
            GenerateInitblk();
            GenerateRethrow();
            GenerateSizeof();
            GenerateRefanytype();
            GenerateReadonly_();
        }

        protected  OpcodeValueAttribute GetOpcodeInfo() => GetOpcodeInfo(new StackTrace().GetFrame(1).GetMethod());

        [OpcodeValue(0)] public abstract void GenerateNop();
        [OpcodeValue(1)] public abstract void GenerateBreak();
        [OpcodeValue(2)] public abstract void GenerateLdarg_0();
        [OpcodeValue(3)] public abstract void GenerateLdarg_1();
        [OpcodeValue(4)] public abstract void GenerateLdarg_2();
        [OpcodeValue(5)] public abstract void GenerateLdarg_3();
        [OpcodeValue(6)] public abstract void GenerateLdloc_0();
        [OpcodeValue(7)] public abstract void GenerateLdloc_1();
        [OpcodeValue(8)] public abstract void GenerateLdloc_2();
        [OpcodeValue(9)] public abstract void GenerateLdloc_3();
        [OpcodeValue(10)] public abstract void GenerateStloc_0();
        [OpcodeValue(11)] public abstract void GenerateStloc_1();
        [OpcodeValue(12)] public abstract void GenerateStloc_2();
        [OpcodeValue(13)] public abstract void GenerateStloc_3();
        [OpcodeValue(14)] public abstract void GenerateLdarg_S();
        [OpcodeValue(15)] public abstract void GenerateLdarga_S();
        [OpcodeValue(16)] public abstract void GenerateStarg_S();
        [OpcodeValue(17)] public abstract void GenerateLdloc_S();
        [OpcodeValue(18)] public abstract void GenerateLdloca_S();
        [OpcodeValue(19)] public abstract void GenerateStloc_S();
        [OpcodeValue(20)] public abstract void GenerateLdnull();
        [OpcodeValue(21)] public abstract void GenerateLdc_I4_M1();
        [OpcodeValue(22)] public abstract void GenerateLdc_I4_0();
        [OpcodeValue(23)] public abstract void GenerateLdc_I4_1();
        [OpcodeValue(24)] public abstract void GenerateLdc_I4_2();
        [OpcodeValue(25)] public abstract void GenerateLdc_I4_3();
        [OpcodeValue(26)] public abstract void GenerateLdc_I4_4();
        [OpcodeValue(27)] public abstract void GenerateLdc_I4_5();
        [OpcodeValue(28)] public abstract void GenerateLdc_I4_6();
        [OpcodeValue(29)] public abstract void GenerateLdc_I4_7();
        [OpcodeValue(30)] public abstract void GenerateLdc_I4_8();
        [OpcodeValue(31)] public abstract void GenerateLdc_I4_S();
        [OpcodeValue(32)] public abstract void GenerateLdc_I4();
        [OpcodeValue(33)] public abstract void GenerateLdc_I8();
        [OpcodeValue(34)] public abstract void GenerateLdc_R4();
        [OpcodeValue(35)] public abstract void GenerateLdc_R8();
        [OpcodeValue(36)] public abstract void GenerateExec_MSIL_I();
        [OpcodeValue(37)] public abstract void GenerateDup();
        [OpcodeValue(38)] public abstract void GeneratePop();
        [OpcodeValue(39)] public abstract void GenerateJmp();
        [OpcodeValue(40)] public abstract void GenerateCall();
        [OpcodeValue(41)] public abstract void GenerateCalli();
        [OpcodeValue(42)] public abstract void GenerateRet();
        [OpcodeValue(43)] public abstract void GenerateBr_S();
        [OpcodeValue(44)] public abstract void GenerateBrfalse_S();
        [OpcodeValue(45)] public abstract void GenerateBrtrue_S();
        [OpcodeValue(46)] public abstract void GenerateBeq_S();
        [OpcodeValue(47)] public abstract void GenerateBge_S();
        [OpcodeValue(48)] public abstract void GenerateBgt_S();
        [OpcodeValue(49)] public abstract void GenerateBle_S();
        [OpcodeValue(50)] public abstract void GenerateBlt_S();
        [OpcodeValue(51)] public abstract void GenerateBne_Un_S();
        [OpcodeValue(52)] public abstract void GenerateBge_Un_S();
        [OpcodeValue(53)] public abstract void GenerateBgt_Un_S();
        [OpcodeValue(54)] public abstract void GenerateBle_Un_S();
        [OpcodeValue(55)] public abstract void GenerateBlt_Un_S();
        [OpcodeValue(56)] public abstract void GenerateBr();
        [OpcodeValue(57)] public abstract void GenerateBrfalse();
        [OpcodeValue(58)] public abstract void GenerateBrtrue();
        [OpcodeValue(59)] public abstract void GenerateBeq();
        [OpcodeValue(60)] public abstract void GenerateBge();
        [OpcodeValue(61)] public abstract void GenerateBgt();
        [OpcodeValue(62)] public abstract void GenerateBle();
        [OpcodeValue(63)] public abstract void GenerateBlt();
        [OpcodeValue(64)] public abstract void GenerateBne_Un();
        [OpcodeValue(65)] public abstract void GenerateBge_Un();
        [OpcodeValue(66)] public abstract void GenerateBgt_Un();
        [OpcodeValue(67)] public abstract void GenerateBle_Un();
        [OpcodeValue(68)] public abstract void GenerateBlt_Un();
        [OpcodeValue(69)] public abstract void GenerateSwitch();
        [OpcodeValue(70)] public abstract void GenerateLdind_I1();
        [OpcodeValue(71)] public abstract void GenerateLdind_U1();
        [OpcodeValue(72)] public abstract void GenerateLdind_I2();
        [OpcodeValue(73)] public abstract void GenerateLdind_U2();
        [OpcodeValue(74)] public abstract void GenerateLdind_I4();
        [OpcodeValue(75)] public abstract void GenerateLdind_U4();
        [OpcodeValue(76)] public abstract void GenerateLdind_I8();
        [OpcodeValue(77)] public abstract void GenerateLdind_I();
        [OpcodeValue(78)] public abstract void GenerateLdind_R4();
        [OpcodeValue(79)] public abstract void GenerateLdind_R8();
        [OpcodeValue(80)] public abstract void GenerateLdind_Ref();
        [OpcodeValue(81)] public abstract void GenerateStind_Ref();
        [OpcodeValue(82)] public abstract void GenerateStind_I1();
        [OpcodeValue(83)] public abstract void GenerateStind_I2();
        [OpcodeValue(84)] public abstract void GenerateStind_I4();
        [OpcodeValue(85)] public abstract void GenerateStind_I8();
        [OpcodeValue(86)] public abstract void GenerateStind_R4();
        [OpcodeValue(87)] public abstract void GenerateStind_R8();
        [OpcodeValue(88)] public abstract void GenerateAdd();
        [OpcodeValue(89)] public abstract void GenerateSub();
        [OpcodeValue(90)] public abstract void GenerateMul();
        [OpcodeValue(91)] public abstract void GenerateDiv();
        [OpcodeValue(92)] public abstract void GenerateDiv_Un();
        [OpcodeValue(93)] public abstract void GenerateRem();
        [OpcodeValue(94)] public abstract void GenerateRem_Un();
        [OpcodeValue(95)] public abstract void GenerateAnd();
        [OpcodeValue(96)] public abstract void GenerateOr();
        [OpcodeValue(97)] public abstract void GenerateXor();
        [OpcodeValue(98)] public abstract void GenerateShl();
        [OpcodeValue(99)] public abstract void GenerateShr();
        [OpcodeValue(100)] public abstract void GenerateShr_Un();
        [OpcodeValue(101)] public abstract void GenerateNeg();
        [OpcodeValue(102)] public abstract void GenerateNot();
        [OpcodeValue(103)] public abstract void GenerateConv_I1();
        [OpcodeValue(104)] public abstract void GenerateConv_I2();
        [OpcodeValue(105)] public abstract void GenerateConv_I4();
        [OpcodeValue(106)] public abstract void GenerateConv_I8();
        [OpcodeValue(107)] public abstract void GenerateConv_R4();
        [OpcodeValue(108)] public abstract void GenerateConv_R8();
        [OpcodeValue(109)] public abstract void GenerateConv_U4();
        [OpcodeValue(110)] public abstract void GenerateConv_U8();
        [OpcodeValue(111)] public abstract void GenerateCallvirt();
        [OpcodeValue(112)] public abstract void GenerateCpobj();
        [OpcodeValue(113)] public abstract void GenerateLdobj();
        [OpcodeValue(114)] public abstract void GenerateLdstr();
        [OpcodeValue(115)] public abstract void GenerateNewobj();
        [OpcodeValue(116)] public abstract void GenerateCastclass();
        [OpcodeValue(117)] public abstract void GenerateIsinst();
        [OpcodeValue(118)] public abstract void GenerateConv_R_Un();
        [OpcodeValue(119)] public abstract void GenerateExec_MSIL_S();
        [OpcodeValue(121)] public abstract void GenerateUnbox();
        [OpcodeValue(122)] public abstract void GenerateThrow();
        [OpcodeValue(123)] public abstract void GenerateLdfld();
        [OpcodeValue(124)] public abstract void GenerateLdflda();
        [OpcodeValue(125)] public abstract void GenerateStfld();
        [OpcodeValue(126)] public abstract void GenerateLdsfld();
        [OpcodeValue(127)] public abstract void GenerateLdsflda();
        [OpcodeValue(128)] public abstract void GenerateStsfld();
        [OpcodeValue(129)] public abstract void GenerateStobj();
        [OpcodeValue(130)] public abstract void GenerateConv_Ovf_I1_Un();
        [OpcodeValue(131)] public abstract void GenerateConv_Ovf_I2_Un();
        [OpcodeValue(132)] public abstract void GenerateConv_Ovf_I4_Un();
        [OpcodeValue(133)] public abstract void GenerateConv_Ovf_I8_Un();
        [OpcodeValue(134)] public abstract void GenerateConv_Ovf_U1_Un();
        [OpcodeValue(135)] public abstract void GenerateConv_Ovf_U2_Un();
        [OpcodeValue(136)] public abstract void GenerateConv_Ovf_U4_Un();
        [OpcodeValue(137)] public abstract void GenerateConv_Ovf_U8_Un();
        [OpcodeValue(138)] public abstract void GenerateConv_Ovf_I_Un();
        [OpcodeValue(139)] public abstract void GenerateConv_Ovf_U_Un();
        [OpcodeValue(140)] public abstract void GenerateBox();
        [OpcodeValue(141)] public abstract void GenerateNewarr();
        [OpcodeValue(142)] public abstract void GenerateLdlen();
        [OpcodeValue(143)] public abstract void GenerateLdelema();
        [OpcodeValue(144)] public abstract void GenerateLdelem_I1();
        [OpcodeValue(145)] public abstract void GenerateLdelem_U1();
        [OpcodeValue(146)] public abstract void GenerateLdelem_I2();
        [OpcodeValue(147)] public abstract void GenerateLdelem_U2();
        [OpcodeValue(148)] public abstract void GenerateLdelem_I4();
        [OpcodeValue(149)] public abstract void GenerateLdelem_U4();
        [OpcodeValue(150)] public abstract void GenerateLdelem_I8();
        [OpcodeValue(151)] public abstract void GenerateLdelem_I();
        [OpcodeValue(152)] public abstract void GenerateLdelem_R4();
        [OpcodeValue(153)] public abstract void GenerateLdelem_R8();
        [OpcodeValue(154)] public abstract void GenerateLdelem_Ref();
        [OpcodeValue(155)] public abstract void GenerateStelem_I();
        [OpcodeValue(156)] public abstract void GenerateStelem_I1();
        [OpcodeValue(157)] public abstract void GenerateStelem_I2();
        [OpcodeValue(158)] public abstract void GenerateStelem_I4();
        [OpcodeValue(159)] public abstract void GenerateStelem_I8();
        [OpcodeValue(160)] public abstract void GenerateStelem_R4();
        [OpcodeValue(161)] public abstract void GenerateStelem_R8();
        [OpcodeValue(162)] public abstract void GenerateStelem_Ref();
        [OpcodeValue(163)] public abstract void GenerateLdelem();
        [OpcodeValue(164)] public abstract void GenerateStelem();
        [OpcodeValue(165)] public abstract void GenerateUnbox_Any();
        [OpcodeValue(179)] public abstract void GenerateConv_Ovf_I1();
        [OpcodeValue(180)] public abstract void GenerateConv_Ovf_U1();
        [OpcodeValue(181)] public abstract void GenerateConv_Ovf_I2();
        [OpcodeValue(182)] public abstract void GenerateConv_Ovf_U2();
        [OpcodeValue(183)] public abstract void GenerateConv_Ovf_I4();
        [OpcodeValue(184)] public abstract void GenerateConv_Ovf_U4();
        [OpcodeValue(185)] public abstract void GenerateConv_Ovf_I8();
        [OpcodeValue(186)] public abstract void GenerateConv_Ovf_U8();
        [OpcodeValue(194)] public abstract void GenerateRefanyval();
        [OpcodeValue(195)] public abstract void GenerateCkfinite();
        [OpcodeValue(198)] public abstract void GenerateMkrefany();
        [OpcodeValue(208)] public abstract void GenerateLdtoken();
        [OpcodeValue(209)] public abstract void GenerateConv_U2();
        [OpcodeValue(210)] public abstract void GenerateConv_U1();
        [OpcodeValue(211)] public abstract void GenerateConv_I();
        [OpcodeValue(212)] public abstract void GenerateConv_Ovf_I();
        [OpcodeValue(213)] public abstract void GenerateConv_Ovf_U();
        [OpcodeValue(214)] public abstract void GenerateAdd_Ovf();
        [OpcodeValue(215)] public abstract void GenerateAdd_Ovf_Un();
        [OpcodeValue(216)] public abstract void GenerateMul_Ovf();
        [OpcodeValue(217)] public abstract void GenerateMul_Ovf_Un();
        [OpcodeValue(218)] public abstract void GenerateSub_Ovf();
        [OpcodeValue(219)] public abstract void GenerateSub_Ovf_Un();
        [OpcodeValue(220)] public abstract void GenerateEndfinally();
        [OpcodeValue(221)] public abstract void GenerateLeave();
        [OpcodeValue(222)] public abstract void GenerateLeave_S();
        [OpcodeValue(223)] public abstract void GenerateStind_I();
        [OpcodeValue(224)] public abstract void GenerateConv_U();
        [OpcodeValue(248)] public abstract void GeneratePrefix7();
        [OpcodeValue(249)] public abstract void GeneratePrefix6();
        [OpcodeValue(250)] public abstract void GeneratePrefix5();
        [OpcodeValue(251)] public abstract void GeneratePrefix4();
        [OpcodeValue(252)] public abstract void GeneratePrefix3();
        [OpcodeValue(253)] public abstract void GeneratePrefix2();
        [OpcodeValue(254)] public abstract void GeneratePrefix1();
        [OpcodeValue(255)] public abstract void GeneratePrefixref();
        [OpcodeValue(65024)] public abstract void GenerateArglist();
        [OpcodeValue(65025)] public abstract void GenerateCeq();
        [OpcodeValue(65026)] public abstract void GenerateCgt();
        [OpcodeValue(65027)] public abstract void GenerateCgt_Un();
        [OpcodeValue(65028)] public abstract void GenerateClt();
        [OpcodeValue(65029)] public abstract void GenerateClt_Un();
        [OpcodeValue(65030)] public abstract void GenerateLdftn();
        [OpcodeValue(65031)] public abstract void GenerateLdvirtftn();
        [OpcodeValue(65033)] public abstract void GenerateLdarg();
        [OpcodeValue(65034)] public abstract void GenerateLdarga();
        [OpcodeValue(65035)] public abstract void GenerateStarg();
        [OpcodeValue(65036)] public abstract void GenerateLdloc();
        [OpcodeValue(65037)] public abstract void GenerateLdloca();
        [OpcodeValue(65038)] public abstract void GenerateStloc();
        [OpcodeValue(65039)] public abstract void GenerateLocalloc();
        [OpcodeValue(65041)] public abstract void GenerateEndfilter();
        [OpcodeValue(65042)] public abstract void GenerateUnaligned_();
        [OpcodeValue(65043)] public abstract void GenerateVolatile_();
        [OpcodeValue(65044)] public abstract void GenerateTail_();
        [OpcodeValue(65045)] public abstract void GenerateInitobj();
        [OpcodeValue(65046)] public abstract void GenerateConstrained_();
        [OpcodeValue(65047)] public abstract void GenerateCpblk();
        [OpcodeValue(65048)] public abstract void GenerateInitblk();
        [OpcodeValue(65050)] public abstract void GenerateRethrow();
        [OpcodeValue(65052)] public abstract void GenerateSizeof();
        [OpcodeValue(65053)] public abstract void GenerateRefanytype();
        [OpcodeValue(65054)] public abstract void GenerateReadonly_();

    }


}
