using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace ILEngine.CodeGenerator
{
    public abstract class ILOpcodeActionGeneratorBase : IILOpcodeActionGenerator
    {
        protected Dictionary<int, Action> opcodeHandlers;
        protected Dictionary<int, OpCodeValueAttribute> opcodeValueAttributes;
        public ILOpcodeActionGeneratorBase()
        {

            opcodeHandlers = new Dictionary<int, Action>();
            opcodeValueAttributes = new Dictionary<int, OpCodeValueAttribute>();
            var methods = this.GetType().GetMethods();
            foreach (var method in methods)
            {
                var opcodeatt = GetOpcodeInfo(method);
                if (!(opcodeatt is null))
                {
                    Action action = (Action)Delegate.CreateDelegate(typeof(Action), this, method);
                    opcodeHandlers.Add(opcodeatt.OpcodeValue, action);
                    opcodeValueAttributes.Add(opcodeatt.OpcodeValue, opcodeatt);
                }
            }

        }

        OpCodeValueAttribute GetOpcodeInfo(MethodBase method) =>
            method.GetCustomAttributes(true).Where(x => x is OpCodeValueAttribute).FirstOrDefault() as OpCodeValueAttribute;


        public void GenerateAll()
        {
            GenerateNop();
            GenerateBreak();
            GenerateLdarg_0();
            GenerateLdarg_1();
            GenerateLdarg_2();
            GenerateLdarg_3();
            GenerateLdloc_0();
            GenerateLdloc_1();
            GenerateLdloc_2();
            GenerateLdloc_3();
            GenerateStloc_0();
            GenerateStloc_1();
            GenerateStloc_2();
            GenerateStloc_3();
            GenerateLdarg_S();
            GenerateLdarga_S();
            GenerateStarg_S();
            GenerateLdloc_S();
            GenerateLdloca_S();
            GenerateStloc_S();
            GenerateLdnull();
            GenerateLdc_I4_M1();
            GenerateLdc_I4_0();
            GenerateLdc_I4_1();
            GenerateLdc_I4_2();
            GenerateLdc_I4_3();
            GenerateLdc_I4_4();
            GenerateLdc_I4_5();
            GenerateLdc_I4_6();
            GenerateLdc_I4_7();
            GenerateLdc_I4_8();
            GenerateLdc_I4_S();
            GenerateLdc_I4();
            GenerateLdc_I8();
            GenerateLdc_R4();
            GenerateLdc_R8();
            GenerateExec_MSIL_I();
            GenerateDup();
            GeneratePop();
            GenerateJmp();
            GenerateCall();
            GenerateCalli();
            GenerateRet();
            GenerateBr_S();
            GenerateBrfalse_S();
            GenerateBrtrue_S();
            GenerateBeq_S();
            GenerateBge_S();
            GenerateBgt_S();
            GenerateBle_S();
            GenerateBlt_S();
            GenerateBne_Un_S();
            GenerateBge_Un_S();
            GenerateBgt_Un_S();
            GenerateBle_Un_S();
            GenerateBlt_Un_S();
            GenerateBr();
            GenerateBrfalse();
            GenerateBrtrue();
            GenerateBeq();
            GenerateBge();
            GenerateBgt();
            GenerateBle();
            GenerateBlt();
            GenerateBne_Un();
            GenerateBge_Un();
            GenerateBgt_Un();
            GenerateBle_Un();
            GenerateBlt_Un();
            GenerateSwitch();
            GenerateLdind_I1();
            GenerateLdind_U1();
            GenerateLdind_I2();
            GenerateLdind_U2();
            GenerateLdind_I4();
            GenerateLdind_U4();
            GenerateLdind_I8();
            GenerateLdind_I();
            GenerateLdind_R4();
            GenerateLdind_R8();
            GenerateLdind_Ref();
            GenerateStind_Ref();
            GenerateStind_I1();
            GenerateStind_I2();
            GenerateStind_I4();
            GenerateStind_I8();
            GenerateStind_R4();
            GenerateStind_R8();
            GenerateAdd();
            GenerateSub();
            GenerateMul();
            GenerateDiv();
            GenerateDiv_Un();
            GenerateRem();
            GenerateRem_Un();
            GenerateAnd();
            GenerateOr();
            GenerateXor();
            GenerateShl();
            GenerateShr();
            GenerateShr_Un();
            GenerateNeg();
            GenerateNot();
            GenerateConv_I1();
            GenerateConv_I2();
            GenerateConv_I4();
            GenerateConv_I8();
            GenerateConv_R4();
            GenerateConv_R8();
            GenerateConv_U4();
            GenerateConv_U8();
            GenerateCallvirt();
            GenerateCpobj();
            GenerateLdobj();
            GenerateLdstr();
            GenerateNewobj();
            GenerateCastclass();
            GenerateIsinst();
            GenerateConv_R_Un();
            GenerateExec_MSIL_S();
            GenerateUnbox();
            GenerateThrow();
            GenerateLdfld();
            GenerateLdflda();
            GenerateStfld();
            GenerateLdsfld();
            GenerateLdsflda();
            GenerateStsfld();
            GenerateStobj();
            GenerateConv_Ovf_I1_Un();
            GenerateConv_Ovf_I2_Un();
            GenerateConv_Ovf_I4_Un();
            GenerateConv_Ovf_I8_Un();
            GenerateConv_Ovf_U1_Un();
            GenerateConv_Ovf_U2_Un();
            GenerateConv_Ovf_U4_Un();
            GenerateConv_Ovf_U8_Un();
            GenerateConv_Ovf_I_Un();
            GenerateConv_Ovf_U_Un();
            GenerateBox();
            GenerateNewarr();
            GenerateLdlen();
            GenerateLdelema();
            GenerateLdelem_I1();
            GenerateLdelem_U1();
            GenerateLdelem_I2();
            GenerateLdelem_U2();
            GenerateLdelem_I4();
            GenerateLdelem_U4();
            GenerateLdelem_I8();
            GenerateLdelem_I();
            GenerateLdelem_R4();
            GenerateLdelem_R8();
            GenerateLdelem_Ref();
            GenerateStelem_I();
            GenerateStelem_I1();
            GenerateStelem_I2();
            GenerateStelem_I4();
            GenerateStelem_I8();
            GenerateStelem_R4();
            GenerateStelem_R8();
            GenerateStelem_Ref();
            GenerateLdelem();
            GenerateStelem();
            GenerateUnbox_Any();
            GenerateConv_Ovf_I1();
            GenerateConv_Ovf_U1();
            GenerateConv_Ovf_I2();
            GenerateConv_Ovf_U2();
            GenerateConv_Ovf_I4();
            GenerateConv_Ovf_U4();
            GenerateConv_Ovf_I8();
            GenerateConv_Ovf_U8();
            GenerateRefanyval();
            GenerateCkfinite();
            GenerateMkrefany();
            GenerateLdtoken();
            GenerateConv_U2();
            GenerateConv_U1();
            GenerateConv_I();
            GenerateConv_Ovf_I();
            GenerateConv_Ovf_U();
            GenerateAdd_Ovf();
            GenerateAdd_Ovf_Un();
            GenerateMul_Ovf();
            GenerateMul_Ovf_Un();
            GenerateSub_Ovf();
            GenerateSub_Ovf_Un();
            GenerateEndfinally();
            GenerateLeave();
            GenerateLeave_S();
            GenerateStind_I();
            GenerateConv_U();
            GeneratePrefix7();
            GeneratePrefix6();
            GeneratePrefix5();
            GeneratePrefix4();
            GeneratePrefix3();
            GeneratePrefix2();
            GeneratePrefix1();
            GeneratePrefixref();
            GenerateArglist();
            GenerateCeq();
            GenerateCgt();
            GenerateCgt_Un();
            GenerateClt();
            GenerateClt_Un();
            GenerateLdftn();
            GenerateLdvirtftn();
            GenerateLdarg();
            GenerateLdarga();
            GenerateStarg();
            GenerateLdloc();
            GenerateLdloca();
            GenerateStloc();
            GenerateLocalloc();
            GenerateEndfilter();
            GenerateUnaligned_();
            GenerateVolatile_();
            GenerateTail_();
            GenerateInitobj();
            GenerateConstrained_();
            GenerateCpblk();
            GenerateInitblk();
            GenerateRethrow();
            GenerateSizeof();
            GenerateRefanytype();
            GenerateReadonly_();
        }

        protected  OpCodeValueAttribute GetOpcodeInfo() => GetOpcodeInfo(new StackTrace().GetFrame(1).GetMethod());

        [OpCodeValue(0)] public abstract void GenerateNop();
        [OpCodeValue(1)] public abstract void GenerateBreak();
        [OpCodeValue(2)] public abstract void GenerateLdarg_0();
        [OpCodeValue(3)] public abstract void GenerateLdarg_1();
        [OpCodeValue(4)] public abstract void GenerateLdarg_2();
        [OpCodeValue(5)] public abstract void GenerateLdarg_3();
        [OpCodeValue(6)] public abstract void GenerateLdloc_0();
        [OpCodeValue(7)] public abstract void GenerateLdloc_1();
        [OpCodeValue(8)] public abstract void GenerateLdloc_2();
        [OpCodeValue(9)] public abstract void GenerateLdloc_3();
        [OpCodeValue(10)] public abstract void GenerateStloc_0();
        [OpCodeValue(11)] public abstract void GenerateStloc_1();
        [OpCodeValue(12)] public abstract void GenerateStloc_2();
        [OpCodeValue(13)] public abstract void GenerateStloc_3();
        [OpCodeValue(14)] public abstract void GenerateLdarg_S();
        [OpCodeValue(15)] public abstract void GenerateLdarga_S();
        [OpCodeValue(16)] public abstract void GenerateStarg_S();
        [OpCodeValue(17)] public abstract void GenerateLdloc_S();
        [OpCodeValue(18)] public abstract void GenerateLdloca_S();
        [OpCodeValue(19)] public abstract void GenerateStloc_S();
        [OpCodeValue(20)] public abstract void GenerateLdnull();
        [OpCodeValue(21)] public abstract void GenerateLdc_I4_M1();
        [OpCodeValue(22)] public abstract void GenerateLdc_I4_0();
        [OpCodeValue(23)] public abstract void GenerateLdc_I4_1();
        [OpCodeValue(24)] public abstract void GenerateLdc_I4_2();
        [OpCodeValue(25)] public abstract void GenerateLdc_I4_3();
        [OpCodeValue(26)] public abstract void GenerateLdc_I4_4();
        [OpCodeValue(27)] public abstract void GenerateLdc_I4_5();
        [OpCodeValue(28)] public abstract void GenerateLdc_I4_6();
        [OpCodeValue(29)] public abstract void GenerateLdc_I4_7();
        [OpCodeValue(30)] public abstract void GenerateLdc_I4_8();
        [OpCodeValue(31)] public abstract void GenerateLdc_I4_S();
        [OpCodeValue(32)] public abstract void GenerateLdc_I4();
        [OpCodeValue(33)] public abstract void GenerateLdc_I8();
        [OpCodeValue(34)] public abstract void GenerateLdc_R4();
        [OpCodeValue(35)] public abstract void GenerateLdc_R8();
        [OpCodeValue(36)] public abstract void GenerateExec_MSIL_I();
        [OpCodeValue(37)] public abstract void GenerateDup();
        [OpCodeValue(38)] public abstract void GeneratePop();
        [OpCodeValue(39)] public abstract void GenerateJmp();
        [OpCodeValue(40)] public abstract void GenerateCall();
        [OpCodeValue(41)] public abstract void GenerateCalli();
        [OpCodeValue(42)] public abstract void GenerateRet();
        [OpCodeValue(43)] public abstract void GenerateBr_S();
        [OpCodeValue(44)] public abstract void GenerateBrfalse_S();
        [OpCodeValue(45)] public abstract void GenerateBrtrue_S();
        [OpCodeValue(46)] public abstract void GenerateBeq_S();
        [OpCodeValue(47)] public abstract void GenerateBge_S();
        [OpCodeValue(48)] public abstract void GenerateBgt_S();
        [OpCodeValue(49)] public abstract void GenerateBle_S();
        [OpCodeValue(50)] public abstract void GenerateBlt_S();
        [OpCodeValue(51)] public abstract void GenerateBne_Un_S();
        [OpCodeValue(52)] public abstract void GenerateBge_Un_S();
        [OpCodeValue(53)] public abstract void GenerateBgt_Un_S();
        [OpCodeValue(54)] public abstract void GenerateBle_Un_S();
        [OpCodeValue(55)] public abstract void GenerateBlt_Un_S();
        [OpCodeValue(56)] public abstract void GenerateBr();
        [OpCodeValue(57)] public abstract void GenerateBrfalse();
        [OpCodeValue(58)] public abstract void GenerateBrtrue();
        [OpCodeValue(59)] public abstract void GenerateBeq();
        [OpCodeValue(60)] public abstract void GenerateBge();
        [OpCodeValue(61)] public abstract void GenerateBgt();
        [OpCodeValue(62)] public abstract void GenerateBle();
        [OpCodeValue(63)] public abstract void GenerateBlt();
        [OpCodeValue(64)] public abstract void GenerateBne_Un();
        [OpCodeValue(65)] public abstract void GenerateBge_Un();
        [OpCodeValue(66)] public abstract void GenerateBgt_Un();
        [OpCodeValue(67)] public abstract void GenerateBle_Un();
        [OpCodeValue(68)] public abstract void GenerateBlt_Un();
        [OpCodeValue(69)] public abstract void GenerateSwitch();
        [OpCodeValue(70)] public abstract void GenerateLdind_I1();
        [OpCodeValue(71)] public abstract void GenerateLdind_U1();
        [OpCodeValue(72)] public abstract void GenerateLdind_I2();
        [OpCodeValue(73)] public abstract void GenerateLdind_U2();
        [OpCodeValue(74)] public abstract void GenerateLdind_I4();
        [OpCodeValue(75)] public abstract void GenerateLdind_U4();
        [OpCodeValue(76)] public abstract void GenerateLdind_I8();
        [OpCodeValue(77)] public abstract void GenerateLdind_I();
        [OpCodeValue(78)] public abstract void GenerateLdind_R4();
        [OpCodeValue(79)] public abstract void GenerateLdind_R8();
        [OpCodeValue(80)] public abstract void GenerateLdind_Ref();
        [OpCodeValue(81)] public abstract void GenerateStind_Ref();
        [OpCodeValue(82)] public abstract void GenerateStind_I1();
        [OpCodeValue(83)] public abstract void GenerateStind_I2();
        [OpCodeValue(84)] public abstract void GenerateStind_I4();
        [OpCodeValue(85)] public abstract void GenerateStind_I8();
        [OpCodeValue(86)] public abstract void GenerateStind_R4();
        [OpCodeValue(87)] public abstract void GenerateStind_R8();
        [OpCodeValue(88)] public abstract void GenerateAdd();
        [OpCodeValue(89)] public abstract void GenerateSub();
        [OpCodeValue(90)] public abstract void GenerateMul();
        [OpCodeValue(91)] public abstract void GenerateDiv();
        [OpCodeValue(92)] public abstract void GenerateDiv_Un();
        [OpCodeValue(93)] public abstract void GenerateRem();
        [OpCodeValue(94)] public abstract void GenerateRem_Un();
        [OpCodeValue(95)] public abstract void GenerateAnd();
        [OpCodeValue(96)] public abstract void GenerateOr();
        [OpCodeValue(97)] public abstract void GenerateXor();
        [OpCodeValue(98)] public abstract void GenerateShl();
        [OpCodeValue(99)] public abstract void GenerateShr();
        [OpCodeValue(100)] public abstract void GenerateShr_Un();
        [OpCodeValue(101)] public abstract void GenerateNeg();
        [OpCodeValue(102)] public abstract void GenerateNot();
        [OpCodeValue(103)] public abstract void GenerateConv_I1();
        [OpCodeValue(104)] public abstract void GenerateConv_I2();
        [OpCodeValue(105)] public abstract void GenerateConv_I4();
        [OpCodeValue(106)] public abstract void GenerateConv_I8();
        [OpCodeValue(107)] public abstract void GenerateConv_R4();
        [OpCodeValue(108)] public abstract void GenerateConv_R8();
        [OpCodeValue(109)] public abstract void GenerateConv_U4();
        [OpCodeValue(110)] public abstract void GenerateConv_U8();
        [OpCodeValue(111)] public abstract void GenerateCallvirt();
        [OpCodeValue(112)] public abstract void GenerateCpobj();
        [OpCodeValue(113)] public abstract void GenerateLdobj();
        [OpCodeValue(114)] public abstract void GenerateLdstr();
        [OpCodeValue(115)] public abstract void GenerateNewobj();
        [OpCodeValue(116)] public abstract void GenerateCastclass();
        [OpCodeValue(117)] public abstract void GenerateIsinst();
        [OpCodeValue(118)] public abstract void GenerateConv_R_Un();
        [OpCodeValue(119)] public abstract void GenerateExec_MSIL_S();
        [OpCodeValue(121)] public abstract void GenerateUnbox();
        [OpCodeValue(122)] public abstract void GenerateThrow();
        [OpCodeValue(123)] public abstract void GenerateLdfld();
        [OpCodeValue(124)] public abstract void GenerateLdflda();
        [OpCodeValue(125)] public abstract void GenerateStfld();
        [OpCodeValue(126)] public abstract void GenerateLdsfld();
        [OpCodeValue(127)] public abstract void GenerateLdsflda();
        [OpCodeValue(128)] public abstract void GenerateStsfld();
        [OpCodeValue(129)] public abstract void GenerateStobj();
        [OpCodeValue(130)] public abstract void GenerateConv_Ovf_I1_Un();
        [OpCodeValue(131)] public abstract void GenerateConv_Ovf_I2_Un();
        [OpCodeValue(132)] public abstract void GenerateConv_Ovf_I4_Un();
        [OpCodeValue(133)] public abstract void GenerateConv_Ovf_I8_Un();
        [OpCodeValue(134)] public abstract void GenerateConv_Ovf_U1_Un();
        [OpCodeValue(135)] public abstract void GenerateConv_Ovf_U2_Un();
        [OpCodeValue(136)] public abstract void GenerateConv_Ovf_U4_Un();
        [OpCodeValue(137)] public abstract void GenerateConv_Ovf_U8_Un();
        [OpCodeValue(138)] public abstract void GenerateConv_Ovf_I_Un();
        [OpCodeValue(139)] public abstract void GenerateConv_Ovf_U_Un();
        [OpCodeValue(140)] public abstract void GenerateBox();
        [OpCodeValue(141)] public abstract void GenerateNewarr();
        [OpCodeValue(142)] public abstract void GenerateLdlen();
        [OpCodeValue(143)] public abstract void GenerateLdelema();
        [OpCodeValue(144)] public abstract void GenerateLdelem_I1();
        [OpCodeValue(145)] public abstract void GenerateLdelem_U1();
        [OpCodeValue(146)] public abstract void GenerateLdelem_I2();
        [OpCodeValue(147)] public abstract void GenerateLdelem_U2();
        [OpCodeValue(148)] public abstract void GenerateLdelem_I4();
        [OpCodeValue(149)] public abstract void GenerateLdelem_U4();
        [OpCodeValue(150)] public abstract void GenerateLdelem_I8();
        [OpCodeValue(151)] public abstract void GenerateLdelem_I();
        [OpCodeValue(152)] public abstract void GenerateLdelem_R4();
        [OpCodeValue(153)] public abstract void GenerateLdelem_R8();
        [OpCodeValue(154)] public abstract void GenerateLdelem_Ref();
        [OpCodeValue(155)] public abstract void GenerateStelem_I();
        [OpCodeValue(156)] public abstract void GenerateStelem_I1();
        [OpCodeValue(157)] public abstract void GenerateStelem_I2();
        [OpCodeValue(158)] public abstract void GenerateStelem_I4();
        [OpCodeValue(159)] public abstract void GenerateStelem_I8();
        [OpCodeValue(160)] public abstract void GenerateStelem_R4();
        [OpCodeValue(161)] public abstract void GenerateStelem_R8();
        [OpCodeValue(162)] public abstract void GenerateStelem_Ref();
        [OpCodeValue(163)] public abstract void GenerateLdelem();
        [OpCodeValue(164)] public abstract void GenerateStelem();
        [OpCodeValue(165)] public abstract void GenerateUnbox_Any();
        [OpCodeValue(179)] public abstract void GenerateConv_Ovf_I1();
        [OpCodeValue(180)] public abstract void GenerateConv_Ovf_U1();
        [OpCodeValue(181)] public abstract void GenerateConv_Ovf_I2();
        [OpCodeValue(182)] public abstract void GenerateConv_Ovf_U2();
        [OpCodeValue(183)] public abstract void GenerateConv_Ovf_I4();
        [OpCodeValue(184)] public abstract void GenerateConv_Ovf_U4();
        [OpCodeValue(185)] public abstract void GenerateConv_Ovf_I8();
        [OpCodeValue(186)] public abstract void GenerateConv_Ovf_U8();
        [OpCodeValue(194)] public abstract void GenerateRefanyval();
        [OpCodeValue(195)] public abstract void GenerateCkfinite();
        [OpCodeValue(198)] public abstract void GenerateMkrefany();
        [OpCodeValue(208)] public abstract void GenerateLdtoken();
        [OpCodeValue(209)] public abstract void GenerateConv_U2();
        [OpCodeValue(210)] public abstract void GenerateConv_U1();
        [OpCodeValue(211)] public abstract void GenerateConv_I();
        [OpCodeValue(212)] public abstract void GenerateConv_Ovf_I();
        [OpCodeValue(213)] public abstract void GenerateConv_Ovf_U();
        [OpCodeValue(214)] public abstract void GenerateAdd_Ovf();
        [OpCodeValue(215)] public abstract void GenerateAdd_Ovf_Un();
        [OpCodeValue(216)] public abstract void GenerateMul_Ovf();
        [OpCodeValue(217)] public abstract void GenerateMul_Ovf_Un();
        [OpCodeValue(218)] public abstract void GenerateSub_Ovf();
        [OpCodeValue(219)] public abstract void GenerateSub_Ovf_Un();
        [OpCodeValue(220)] public abstract void GenerateEndfinally();
        [OpCodeValue(221)] public abstract void GenerateLeave();
        [OpCodeValue(222)] public abstract void GenerateLeave_S();
        [OpCodeValue(223)] public abstract void GenerateStind_I();
        [OpCodeValue(224)] public abstract void GenerateConv_U();
        [OpCodeValue(248)] public abstract void GeneratePrefix7();
        [OpCodeValue(249)] public abstract void GeneratePrefix6();
        [OpCodeValue(250)] public abstract void GeneratePrefix5();
        [OpCodeValue(251)] public abstract void GeneratePrefix4();
        [OpCodeValue(252)] public abstract void GeneratePrefix3();
        [OpCodeValue(253)] public abstract void GeneratePrefix2();
        [OpCodeValue(254)] public abstract void GeneratePrefix1();
        [OpCodeValue(255)] public abstract void GeneratePrefixref();
        [OpCodeValue(65024)] public abstract void GenerateArglist();
        [OpCodeValue(65025)] public abstract void GenerateCeq();
        [OpCodeValue(65026)] public abstract void GenerateCgt();
        [OpCodeValue(65027)] public abstract void GenerateCgt_Un();
        [OpCodeValue(65028)] public abstract void GenerateClt();
        [OpCodeValue(65029)] public abstract void GenerateClt_Un();
        [OpCodeValue(65030)] public abstract void GenerateLdftn();
        [OpCodeValue(65031)] public abstract void GenerateLdvirtftn();
        [OpCodeValue(65033)] public abstract void GenerateLdarg();
        [OpCodeValue(65034)] public abstract void GenerateLdarga();
        [OpCodeValue(65035)] public abstract void GenerateStarg();
        [OpCodeValue(65036)] public abstract void GenerateLdloc();
        [OpCodeValue(65037)] public abstract void GenerateLdloca();
        [OpCodeValue(65038)] public abstract void GenerateStloc();
        [OpCodeValue(65039)] public abstract void GenerateLocalloc();
        [OpCodeValue(65041)] public abstract void GenerateEndfilter();
        [OpCodeValue(65042)] public abstract void GenerateUnaligned_();
        [OpCodeValue(65043)] public abstract void GenerateVolatile_();
        [OpCodeValue(65044)] public abstract void GenerateTail_();
        [OpCodeValue(65045)] public abstract void GenerateInitobj();
        [OpCodeValue(65046)] public abstract void GenerateConstrained_();
        [OpCodeValue(65047)] public abstract void GenerateCpblk();
        [OpCodeValue(65048)] public abstract void GenerateInitblk();
        [OpCodeValue(65050)] public abstract void GenerateRethrow();
        [OpCodeValue(65052)] public abstract void GenerateSizeof();
        [OpCodeValue(65053)] public abstract void GenerateRefanytype();
        [OpCodeValue(65054)] public abstract void GenerateReadonly_();

    }


}
